version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Japan
    networks:
      - default
    ports:
      - '3306:3306'
  web:
    build: .
    volumes:
      - ../scraping-on-scrapy:/tmp/scraping-on-scrapy
    networks:
      - default
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TZ=Japan
    tty: true