version: '2'
services:
  db:
    image: mongo
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/init/:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=scrapy
  web:
    build: .
    volumes:
      - ./:/tmp/scraping-on-scrapy
    networks:
      - default
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TZ=Japan
    tty: true